### ISSUE TITLE
Forgotten worlds (USA) (rev-a) unplayable

### ISSUE THREAD

**Issue by mahoneyt944** [analoguejb/Analogue-Mega-Sg-JB#13]
Once you start a game, it goes immediately to a game over.

**Comment by mahoneyt944** [comment]
Holding the mode button while launching the game fixes the issue, so seems to be a known controller issue.

Under hardware, forcing 3 button mode, also fixes the issue. This option seems to allow the 8bitdo menu button to still function where holding the mode button solution does not.

Forcing 3 button mode is ideal, but it would be nice to automatically do this for known games which must use 3 button mode to be playable.

**Comment by tjanas** [comment]
Instead, maybe someone could make a romhack for those few games that would make them compatible with 6-button mode.

**Comment by mahoneyt944** [comment]
I'd image rom hacks are doable but may not be ideal for people using an original cartridge or purists, though the mode button solution works in this case anyways so its not a big issue. Just overall a clunky solution from sega in my opinion, figured it might be a nice solution to compile a list of known games to automatically enable 3 button mode by default. With a new option to "force 3 button mode" (on / off / auto) to account for this.

**Comment by tjanas** [comment]
https://youtu.be/x_2fLD3EKKw

**Comment by mahoneyt944** [comment]
That's a nice list of games, nice reference. I would think if we could add these games to an external config file then users could create a list of games to automatically force 3 button mode.
